export default {
  workspaceRoot: '.',
  baselineFile: 'architecture-baseline.json',
  frontendWorkspaceFiles: [
    'apps/web/src/components/ClientWorkspacePanel.tsx',
    'apps/web/src/components/ClientTaxesTab.tsx',
    'apps/web/src/components/ClientBusinessProfileTab.tsx',
    'apps/web/src/components/ClientAccountingSettingsTab.tsx',
    'apps/web/src/components/ClientObligationsTab.tsx',
    'apps/web/src/components/ClientDocumentsTab.tsx',
    'apps/web/src/components/ClientAnnualReportTab.tsx',
    'apps/web/src/components/ClientFeesTab.tsx',
    'apps/web/src/components/ClientPayrollTab.tsx',
    'apps/web/src/components/ClientHistoryTab.tsx',
  ],
  backendRouteRoots: ['apps/api/src/domains/client-operations'],
  backendRouteFilePattern: /routes\.ts$/,
  endpointRegistryFile: 'apps/web/src/api/endpoints.ts',
  allowedCommandEndpointPatterns: [/Commands\(/, /\/commands['"`)]?$/i],
  allowedOperationalReadEndpoints: [
    /FileOpen/i,
    /HistoryExport/i,
    /reveal-payment-secret/i,
  ],
  allowedOperationalWriteEndpoints: [
    /Upload/i,
    /request-code/i,
    /verify-code/i,
    /reveal-payment-secret/i,
  ],
  forbiddenWorkspaceTruthEndpoints: [
    /TaxSettings\(/,
    /AccountingSettingsTab\(/,
    /BlockModal\(/,
    /normalize-draft/i,
    /modal-visibility/i,
    /VehicleFleetItemModal/i,
  ],
  deprecatedLegacyEndpoints: [
    /moduleClientOperationsUpdateClientProfile/,
    /moduleClientOperationsAccountingGeneral/,
    /moduleClientOperationsAccountingVehicles/,
    /moduleClientOperationsAccountingBusinessProfile/,
    /moduleClientOperationsTaxSettings/,
  ],
  accountingBaseReferencePatterns: [
    /accounting[_-]?base/i,
    /accounting[_-]?entries/i,
    /AccountingBase/i,
  ],
  countryPackReferencePatterns: [
    /country[_-]?pack/i,
    /CountryPack/i,
    /ruleset/i,
    /owner[_ -]?legal[_ -]?control[_ -]?panel/i,
    /legal[_ -]?values/i,
  ],
  temporaryAccountingPendingMarker: 'TEMPORARY_ACCOUNTING_BASE_PENDING',
  temporaryCountryPackPendingMarker: 'TEMPORARY_COUNTRY_PACK_PENDING',
  financialTruthKeywords: [
    'amount',
    'total',
    'totals',
    'income',
    'expense',
    'payment',
    'payroll',
    'fee',
    'fees',
    'balance',
    'balances',
    'financialSummary',
    'financial_summary',
  ],
  countrySpecificKeywords: [
    'vat',
    'מע"מ',
    'מעמ',
    'מס הכנסה',
    'ביטוח לאומי',
    'due date',
    'filing deadline',
    'report deadline',
    'statutory',
    'compliance calendar',
    'credit point',
    'נקודת זיכוי',
    'נקודות זיכוי',
    'legal rate',
    'legal limit',
    'local document type',
    'local validation',
  ],
  legacyEndpointSymbols: [
    'moduleClientOperationsUpdateClientProfile',
    'moduleClientOperationsAccountingGeneral',
    'moduleClientOperationsAccountingVehicles',
    'moduleClientOperationsAccountingBusinessProfile',
    'moduleClientOperationsTaxSettings',
  ],
  semanticFields: [
    'status',
    'priority',
    'due',
    'deadline',
    'column',
    'columns',
    'group',
    'section',
    'owner',
    'ownership',
    'type',
    'types',
    'action',
    'actions',
    'label',
    'labels',
    'badge',
    'color',
    'available',
    'can_',
    'submitted',
    'overdue',
  ],
  presentationalConditionAllowPatterns: [
    /isOpen|open|busy|loading|error|hover|focus|selected|expanded|collapsed/i,
    /className|style|theme|dark|light/i,
  ],
  tableOwnershipAllowVarPatterns: [
    /layout|grid|ui|style|classNames/i,
  ],
  allowLocalStateSetters: [
    'setDraft',
    'setNotesDraft',
    'setFieldErrors',
    'setSaveErrorHe',
    'setSaveSuccessHe',
    'setSaveBusy',
    'setBusy',
    'setErr',
    'setUploadTarget',
    'setSubmissionDlg',
    'setNoteLocal',
    'setEditOpen',
    'setOpen',
    'setModalOpen',
    'setActiveTab',
    'setOpenSection',
  ],
  fullReplaceEvidencePatterns: [
    /setLocalWorkspace\(/,
    /onCaseUpdated\(/,
    /onTaxSettingsUpdated\(/,
    /onAccountingCaseUpdated\(/,
  ],
  partialUpdateSuspiciousPatterns: [
    /set[A-Z]\w+\s*\(\s*\(?prev\)?\s*=>/,
    /queryClient\.setQueryData\(/,
    /cache\.(update|set|patch)/,
    /\.map\(\s*\(/,
    /Object\.assign\(\s*prev/,
    /\{\s*\.\.\.\s*prev/,
  ],
  backendPatchPutAllowlist: [],
  frontendPatchPutAllowlist: [],
};
