/**
 * INV-13A — Seed Owner layout V1 from CURRENT SECTIONED_GOLDEN_MASTER.
 * Do not redesign — structural equivalent of approved sectioned invoice.
 */

import { SECTIONED_GOLDEN_MASTER } from '../income/income-document-sectioned-golden-master.pure.js';
import { parseAndValidateOwnerInvoiceLayoutDefinition } from './owner-invoice-document-layout-schema.pure.js';
import type { OwnerInvoiceLayoutDefinitionV1 } from './owner-invoice-document-layout.types.js';

const GM = SECTIONED_GOLDEN_MASTER;

/**
 * Builds schema_version=1 definition that mirrors current sectioned layout zones,
 * field set, and table columns used by the unified renderer.
 */
export function buildSectionedGoldenMasterLayoutDefinitionV1(): OwnerInvoiceLayoutDefinitionV1 {
  const raw = {
    schema_version: 1,
    grid: {
      columns: 12,
      page: {
        width_px: GM.page.a4_width_px,
        height_px: GM.page.a4_height_px,
      },
      snap_px: 8,
    },
    sections: [
      {
        key: 'issuer_branding',
        order: 0,
        zone: 'upper',
        col_start: 7,
        col_span: 6,
        min_height_px: 120,
        max_height_px: 420,
        height_px: 200,
        alignment: 'start',
        visible: true,
        owner_locked: true,
      },
      {
        key: 'document_identity',
        order: 1,
        zone: 'upper',
        col_start: 1,
        col_span: 6,
        min_height_px: 120,
        max_height_px: 420,
        height_px: 200,
        alignment: 'start',
        visible: true,
        owner_locked: true,
      },
      {
        key: 'customer',
        order: 2,
        zone: 'upper',
        col_start: 1,
        col_span: 6,
        min_height_px: 80,
        max_height_px: 320,
        height_px: Math.max(80, GM.upper.customer_card_height_px || 160),
        alignment: 'start',
        visible: true,
        owner_locked: false,
      },
      {
        key: 'lines',
        order: 3,
        zone: 'body',
        col_start: 1,
        col_span: 12,
        min_height_px: GM.table.header_height_px + GM.table.row_height_px,
        max_height_px: 900,
        height_px: GM.table.header_height_px + GM.table.row_height_px * 2,
        alignment: 'stretch',
        visible: true,
        owner_locked: true,
      },
      {
        key: 'notes',
        order: 4,
        zone: 'lower',
        col_start: 1,
        col_span: 6,
        min_height_px: 80,
        max_height_px: 400,
        height_px: Math.min(204, GM.lower.notes_totals_height_px),
        alignment: 'stretch',
        visible: true,
        owner_locked: false,
      },
      {
        key: 'totals',
        order: 5,
        zone: 'lower',
        col_start: 7,
        col_span: 6,
        min_height_px: 80,
        max_height_px: 400,
        height_px: Math.min(204, GM.lower.notes_totals_height_px),
        alignment: 'stretch',
        visible: true,
        owner_locked: true,
      },
      {
        key: 'payments',
        order: 6,
        zone: 'lower',
        col_start: 1,
        col_span: 12,
        min_height_px: 80,
        max_height_px: 260,
        height_px: GM.lower.payment_card_height_px,
        alignment: 'stretch',
        visible: true,
        owner_locked: false,
      },
      {
        key: 'legal_footer',
        order: 7,
        zone: 'lower',
        col_start: 1,
        col_span: 12,
        min_height_px: 32,
        max_height_px: 120,
        height_px: GM.lower.footer_height_px,
        alignment: 'stretch',
        visible: true,
        owner_locked: true,
      },
    ],
    fields: [
      { field_key: 'logo', section_key: 'issuer_branding', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'issuer_name', section_key: 'issuer_branding', order: 1, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'tax_id', section_key: 'issuer_branding', order: 2, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'address', section_key: 'issuer_branding', order: 3, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'phone', section_key: 'issuer_branding', order: 4, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'email', section_key: 'issuer_branding', order: 5, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'website', section_key: 'issuer_branding', order: 6, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'document_type', section_key: 'document_identity', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'document_number', section_key: 'document_identity', order: 1, visible: true, width_span: 12, display_variant: 'number_bar', owner_locked: true },
      { field_key: 'issue_date', section_key: 'document_identity', order: 2, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'due_date', section_key: 'document_identity', order: 3, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'tax_allocation_number', section_key: 'document_identity', order: 4, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'payment_terms', section_key: 'document_identity', order: 5, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'customer_name', section_key: 'customer', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'customer_tax_id', section_key: 'customer', order: 1, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'customer_address', section_key: 'customer', order: 2, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'customer_email', section_key: 'customer', order: 3, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'customer_phone', section_key: 'customer', order: 4, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'line_description', section_key: 'lines', order: 0, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: true },
      { field_key: 'line_quantity', section_key: 'lines', order: 1, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: true },
      { field_key: 'line_unit_price', section_key: 'lines', order: 2, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: true },
      { field_key: 'line_currency', section_key: 'lines', order: 3, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: false },
      { field_key: 'line_vat', section_key: 'lines', order: 4, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: true },
      { field_key: 'line_total', section_key: 'lines', order: 5, visible: true, width_span: 12, display_variant: 'table_column', owner_locked: true },
      { field_key: 'subtotal', section_key: 'totals', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'vat_total', section_key: 'totals', order: 1, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'grand_total', section_key: 'totals', order: 2, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'notes', section_key: 'notes', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'signature_block', section_key: 'payments', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
      { field_key: 'legal_wording', section_key: 'legal_footer', order: 0, visible: true, width_span: 12, display_variant: 'default', owner_locked: true },
      { field_key: 'platform_footer', section_key: 'legal_footer', order: 1, visible: true, width_span: 12, display_variant: 'default', owner_locked: false },
    ],
    table: {
      columns: [
        { key: 'index', order: 0, visible: true, width_px: 36, align: 'center', owner_locked: true },
        { key: 'line_description', order: 1, visible: true, width_px: null, align: 'start', owner_locked: true },
        { key: 'line_quantity', order: 2, visible: true, width_px: 64, align: 'center', owner_locked: true },
        { key: 'line_unit_price', order: 3, visible: true, width_px: 96, align: 'end', owner_locked: true },
        { key: 'line_currency', order: 4, visible: true, width_px: 64, align: 'center', owner_locked: false },
        { key: 'line_vat', order: 5, visible: true, width_px: 64, align: 'center', owner_locked: true },
        { key: 'line_total', order: 6, visible: true, width_px: 104, align: 'end', owner_locked: true },
      ],
    },
    user_branding_bounds: {
      logo_size_keys_allowed: ['small', 'medium', 'large'],
      color_theme_keys_allowed: [
        'nodexpro_premium',
        'black_white',
        'pastel_purple',
        'teal',
        'dark_blue',
        'gray',
        'pale_peach',
        'pale_green',
        'pale_mint',
        'pale_blue',
        'red',
        'bright_blue',
        'green',
        'yellow',
      ],
    },
  };

  return parseAndValidateOwnerInvoiceLayoutDefinition(raw);
}

/** Structural markers proving seed matches current sectioned GM zones. */
export function sectionedGoldenMasterSeedStructuralMarkers(): string[] {
  return [
    'issuer_branding',
    'document_identity',
    'customer',
    'lines',
    'totals',
    'notes',
    'payments',
    'legal_footer',
    'document_number',
    'tax_allocation_number',
    'line_vat',
    'vat_total',
    'grand_total',
    'logo',
  ];
}
